"""
Python UNO Macro for LibreOffice Writer
Demonstrates document text manipulation via UNO API
"""

import uno

def insert_text_in_writer():
    """
    Insert formatted text into a Writer document using Python UNO.
    """
    try:
        doc = XSCRIPTCONTEXT.getDocument()
        text = doc.Text
        cursor = text.createTextCursor()
        
        # Insert heading
        text.insertString(cursor, "LibreOffice UNO Python Macro Demo\n", False)
        cursor.ParaStyleName = "Heading 1"
        
        # Insert body text
        cursor = text.createTextCursor()
        cursor.gotoEnd(False)
        
        body_text = "This document was generated by a Python macro using the UNO API. "
        body_text += "You can automate Writer documents programmatically with Python!"
        
        text.insertString(cursor, body_text, False)
        
        return "✓ Text inserted successfully!"
    
    except Exception as e:
        return f"✗ Error: {str(e)}"
